### ISSUE TITLE
How can I test pose ?

### ISSUE THREAD

**Issue by Tokymin** [JiawangBian/sc_depth_pl#17]
Hi dear author, I want to know how to test pose accuracy since I didn't find ground pose in the dataset that you provided.
![图片](https://user-images.githubusercontent.com/32712253/186907906-d0abcc68-d94c-4133-a6fe-0b3a90612d66.png)

**Comment by JiawangBian** [comment]
This is KITTI raw dataset for depth estimation. If you need to test pose accuracy, you need to download KITTI odometry datasets. I may provide it in this repo in the future, but for now, you can refer to https://github.com/JiawangBian/SC-SfMLearner-Release

**Comment by JiawangBian** [comment]
As the 5-frame pose evaluation is not a good metric to evaluate pose accuracy. I prefer not doing that.

**Comment by Tokymin** [comment]
> 

I'm sorry, what is the exact meaning of the 5-frame pose evaluation metric? Do you mean the pose performance of SC models is not good enough?

**Comment by JiawangBian** [comment]
> > 
> 
> I'm sorry, what is the exact meaning of the 5-frame pose evaluation metric? Do you mean the pose performance of SC models is not good enough?

I mean that the pose accuracy evaluation method (proposed in SfMLearner, it evaluates pose accuracy every 5 frames, I guess that you want to do such an evaluation here.) is not reasonable.

**Comment by Tokymin** [comment]
> > > 
> > 
> > 
> > I'm sorry, what is the exact meaning of the 5-frame pose evaluation metric? Do you mean the pose performance of SC models is not good enough?
> 
> I mean that the pose accuracy evaluation method (proposed in SfMLearner, it evaluates pose accuracy every 5 frames, I guess that you want to do such an evaluation here.) is not reasonable.

yeah, I am more concerned about the pose accuracy instead of depth in my project, and I want to test the efficiency of loss you proposed using my own dataset.  Unfortunately, the 3D re-project process, that is the 'inverse_warp' function, is not passed on (it seems not corrected). I was so confused now. I'm not sure if some problems in my dataset. so I would like to ask how to verify the effectiveness of unsupervised loss in the network. How did you do at that time?

**Comment by JiawangBian** [comment]
See visual odometry evaluation in  https://github.com/JiawangBian/SC-SfMLearner-Release
