### ISSUE TITLE
quat2mat

### ISSUE THREAD

**Issue by ZhiyiHe1997** [JiawangBian/sc_depth_pl#18]
https://github.com/JiawangBian/sc_depth_pl/blob/2f76ce86524188c1ac04d0d1d4a9bd45eb3902e0/losses/inverse_warp.py#L63
if we use the quaternion coefficients as shown in image1
![image](https://user-images.githubusercontent.com/101542171/187644137-3fb07feb-a48e-49d5-8230-68e48ebca704.png)
according to the Rodriguez formula，We can deduce the rotation matrix，as shown in image2
![image](https://user-images.githubusercontent.com/101542171/187644213-66bbd153-b2df-4f83-b854-30f54e9e111b.png)
i find there are difference between formula and codes. Could you tell me the details of the changes you have made?

**Comment by JiawangBian** [comment]
Just copied from https://github.com/ClementPinard/SfmLearner-Pytorch/blob/master/inverse_warp.py. Didn't use it.

**Comment by ZhiyiHe1997** [comment]
yes, i saw it, may i ask it will influence the results?
have you think adout this trick?

**Comment by JiawangBian** [comment]
You can try this one "https://kornia.readthedocs.io/en/latest/_modules/kornia/geometry/conversions.html#quaternion_to_rotation_matrix" if you need it.

**Comment by JiawangBian** [comment]
> yes, i saw it, may i ask it will influence the results? have you think adout this trick?

I tried it before and got very similar results compared to using euler angle on KITTI.

**Comment by ZhiyiHe1997** [comment]
ok , thanks for your reply. i will try it later. 
Best regards.
