### ISSUE TITLE
Test with median scaling?

### ISSUE THREAD

**Issue by JinraeKim** [JiawangBian/sc_depth_pl#19]
Hi, I'm interested in your impressive work!

If I understood correctly, this algorithm produces scale-consistent depth and pose estimation, so as mentioned in the paper, one does not need to do median scaling per frame (instead, only a single scaling factor would be enough).

However, in the code, I found that you still use median scaling per frame in `test.py` (see `compute_errors`. Sorry, I'm using my phone now so it's hard to paste the link).

That is different from what you mentioned in the paper:

> Note that the comparison is highly disadvantageous to the proposed method: i)we align per-frame scale to the ground truth scale for [7] due to its scale-inconsistency, while we only align one global scale for our method.

**Comment by JiawangBian** [comment]
1. "test.py" is for depth evaluation. We do median-scaling for all methods for fair comparison.

2. " i)we align per-frame scale to the ground truth scale for [7] due to its scale-inconsistency, while we only align one global scale for our method": It is for visual odometry evaluation.
