### ISSUE TITLE
Training and testing pose

### ISSUE THREAD

**Issue by hemangchawla** [JiawangBian/sc_depth_pl#2]
Hi,

Do you have corresponding scripts for training and testing the pose with your method?

Thanks

**Comment by JiawangBian** [comment]
currently no, but I may provide soon if I have time. If you need it, you can write it by yourself. You just need to train models with "--val_mode=photo".

**Comment by Tokymin** [comment]
@JiawangBian And then what? Could you give me more advice? Thank you~

**Comment by Tokymin** [comment]
Hi, @hemangchawla Have you solved the problem? Could you give me some advice?

**Comment by Tokymin** [comment]
I have solved the problem, There is no need to reply to me, Thanks.

**Comment by belkahorry** [comment]
Hi,so how did you deal with it?

**Comment by Tokymin** [comment]
> Hi,so how did you deal with it?

change the way to load the test dataset, just like the TrainFolder, making sure there are 'tgt_img, ref_imgs, intrinsics' when testing.
