### ISSUE TITLE
how to reconstruct the point clouds with a depth map?

### ISSUE THREAD

**Issue by sandstorm666** [JiawangBian/sc_depth_pl#21]

**Comment by sandstorm666** [comment]
I used rgb-d camera,rgb-d camera has a variabled called depthScale，depth=1/depthScale。

**Comment by JiawangBian** [comment]
See Open3D for point cloud operation.

http://www.open3d.org/docs/release/python_api/open3d.geometry.RGBDImage.html

**Comment by sandstorm666** [comment]
> See Open3D for point cloud operation.
> 
> http://www.open3d.org/docs/release/python_api/open3d.geometry.RGBDImage.html

Why is the color map in nyu 640 * 480, the predicted depth map 320 * 256, and the depth map given by nyu 640 * 480。i run the inference.py。

**Comment by sandstorm666** [comment]
> See Open3D for point cloud operation.
> 
> http://www.open3d.org/docs/release/python_api/open3d.geometry.RGBDImage.html



> See Open3D for point cloud operation.
> 
> http://www.open3d.org/docs/release/python_api/open3d.geometry.RGBDImage.html

I used the pre training weight you gave me to test 0001.jpg of the nyu dataset, but the results were different. The depth map obtained was zoomed in. I zoomed in to the same size as the original image, and the results were incorrect.

**Comment by sandstorm666** [comment]
![2022-10-27 18-16-36 的屏幕截图](https://user-images.githubusercontent.com/73341998/198259217-9571e4ff-3cc0-437a-af34-04cf53848861.png) 
The first picture is provided in your paper。
![0001](https://user-images.githubusercontent.com/73341998/198259516-e6996e85-edee-4800-8728-729c51c4cae0.png)
I found this photo in nyu dataset.then ℹ run the command.
```
python inference.py --config configs/v2/nyu.txt \
--input_dir demo/input/ \
--output_dir demo/output/ \
--ckpt_path ckpts/nyu_scv2/version_10/epoch=101-val_loss=0.1580.ckpt \
--save-vis --save-depth
```
![0001](https://user-images.githubusercontent.com/73341998/198260771-cc6db40d-8205-4c60-87b5-09e17cd33b63.jpg)
I used the pre training weights you provided, but the results are different from yours. Did you make any changes?

**Comment by JiawangBian** [comment]
It is due to image borders. You can find that the image has white borders which cause a very large depth value. If you crop the image, the visual results will be OK. Otherwise, you can change the visualization code.

**Comment by sandstorm666** [comment]
thks, the performance is much better than before, but why is the depth map generated by default scaled?
`training_size = `[256, 320]

**Comment by JiawangBian** [comment]
To save space. It is the original output of the network, so you can upsample or downsample it depending on your problems.
