### ISSUE TITLE
depthmap

### ISSUE THREAD

**Issue by sandstorm666** [JiawangBian/sc_depth_pl#24]
Can I use the depthmap generated by sc_depth for dense mapping? I want to use the built map to navigate outdoors.

**Comment by JiawangBian** [comment]
Yes. I have shown such a demo in the IJCV paper.

**Comment by sandstorm666** [comment]
The depth value predicted by sc_depth network is the real depth value?

**Comment by sandstorm666** [comment]
太强了，这个v3救大命了，边神！！！更新速度太给力了

**Comment by sandstorm666** [comment]
I am studying your paper. Is the output of network prediction absolute depth or relative depth?

**Comment by JiawangBian** [comment]
Relative depth. it is up to an unknown scale
