### ISSUE TITLE
Error in  (python generate_valid_frame_index.py --dataset_dir $DATASET)

### ISSUE THREAD

**Issue by wjlszhang** [JiawangBian/sc_depth_pl#26]
Hello @JiawangBian 

Before I train my own data, I use generate_valid_frame_indx to settle down the pics, but always get follow error. Much appreciated if you can give some advice.
![d48ff27e724db6e95d1368d21df1a8c](https://user-images.githubusercontent.com/101317599/202605372-15ec5280-9240-48b4-838f-bb4994092660.jpg)

**Comment by JiawangBian** [comment]
It is a simple opencv- based optical flow. It seems that no points are detected in your image. You may try to change the parameter for detecting more points，or you need to check whether your image has texture in both left and right sides.
