### ISSUE TITLE
BONN and TUM depth

### ISSUE THREAD

**Issue by Uhall** [JiawangBian/sc_depth_pl#29]
Hi,
What is the scale coefficient of the depth ground truth images in the BONN and TUM dataset you provided? I only found out how to deal with nyu, kitti and ddad.
```
if self.dataset == 'nyu':
    depth = torch.from_numpy(
        imread(self.depth[index]).astype(np.float32)).float()/5000
elif self.dataset == 'kitti' or self.dataset == 'ddad':
    depth = torch.from_numpy(load_sparse_depth(
        self.depth[index]).astype(np.float32))
```
Looking forward to your reply. Thanks.

**Comment by JiawangBian** [comment]
sorry for the inconvenience. I have updated it.

**Comment by Uhall** [comment]
Thank you so much for the speedy reply.
