### ISSUE TITLE
error

### ISSUE THREAD

**Issue by andy500** [JiawangBian/sc_depth_pl#3]
inference.py: error: Unable to open config file: $CONFIG. Error: No such file or directory why do l get this error 
test.py: error: Unable to open config file: $CONFIG. Error: No such file or directory
inference.py: error: Unable to open config file: configs. Error: Permission denied

**Comment by JiawangBian** [comment]
Please provide the correct path of your configuration file to $CONFIG.

**Comment by andy500** [comment]
Thanks but still get the error am using DPT-main code  am finding this code
much easy to use without errors you might look at this and find how to
setup a python code that doesn't have error when first run it
