### ISSUE TITLE
kitti dataset

### ISSUE THREAD

**Issue by sandstorm666** [JiawangBian/sc_depth_pl#33]
I downloaded the kitti dataset you provided, do you know their timestamps? I want to test it under ORB-SLAM3, I downloaded the odometry data set (color, 65 GB) and can't find the correspondence. The folders inside are named by serial number, not date.
![ZCC6NKL6_4Y236(6 C0 2~5](https://user-images.githubusercontent.com/73341998/203737600-b081eb5a-8401-4701-90a4-ad89a8b8a5ce.png)

**Comment by JiawangBian** [comment]
I provided the raw Kitti dataset for depth estimation evaluation only. For pose evaluation, as done in sfmlearner and other related works, the model should be trained on sequence 00-08 and tested on 09 - 10. However, you can try the model I provided in this repo, although it is not unfair.

**Comment by sandstorm666** [comment]
Do you mean I should use the depth map generated by sfm_learner to provide to SLAM?
![E6YWH737BB1HZTYTT(P(8HJ](https://user-images.githubusercontent.com/73341998/203759383-fb52a2d2-8678-46d2-b32a-cfd73d53fdae.png)
I would like to imitate this behavior in the picture.

**Comment by JiawangBian** [comment]
No...     If you don't have a timestamp, you just need to generate it. For example, you can simply set 1, 2, 3, 4... for each frame, and remember to modify a bit in orb-slam.

**Comment by JiawangBian** [comment]
You can use the depth model that I provided to generate the depth map for the odometry dataset that you download.

**Comment by sandstorm666** [comment]
> I provided the raw Kitti dataset for depth estimation evaluation only. For pose evaluation, as done in sfmlearner and other related works, the model should be trained on sequence 00-08 and tested on 09 - 10. However, you can try the model I provided in this repo as a toy experiment, although it is unfair.

Would it be better to use sfm_learner then?

**Comment by JiawangBian** [comment]
No. sfmlearner just defines a training/test split (00-08 to train, and 09-10 to test), so that all methods could be fairly compared.

**Comment by sandstorm666** [comment]
Can I use imu data to recover the absolute scale of the predicted depth map？depthmap*scale=absolute depthmap?

**Comment by JiawangBian** [comment]
> Can I use imu data to recover the absolute scale of the predicted depth map？depthmap*scale=absolute depthmap?

Yes, you can compute scale by comparing it with the network-predicted pose.

**Comment by sandstorm666** [comment]
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 88 but got size 87 for tensor number 1 in the list.
If I input the original image size of kitti 1392 * 512, an error will occur.
How to solve this problem?

**Comment by JiawangBian** [comment]
Change the resolution. It should be able to be divided by 32, e.g., 1376x512.
