### ISSUE TITLE
what's the measurement unit of depth ?

### ISSUE THREAD

**Issue by wjlszhang** [JiawangBian/sc_depth_pl#35]
Hi, @JiawangBian 

I tried my own data with V3, I found the output depths were like [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44].  Actually I took the picturess with distance around 10cms, thus I wonder what's the measurment unit of the depth in output depth file? It seems neither mm nor cm.

Thanks you so much!

**Comment by chunqizhang** [comment]
I think it's a relative depth. If you set the maximum depth as 100, which corresponds to 10 cm, then 20 is (20/100)*10cm. Usually, the median method is used to get the depth.

**Comment by chunqizhang** [comment]
你好，我想问下你用自己的数据集训练的时候有出现RuntimeError: DataLoader worker (pid 431) is killed by signal: Killed. 这样的错误吗？？
我在不改变参数的情况下运行了官方给的数据集没报错，用自己的数据集报错了，用的命令都是
!python train.py --config configs/v3/ddad.txt --dataset_dir ddad --val_mode photo

**Comment by wjlszhang** [comment]
No, I haven't that error, you may fix it by resize your image size with the same as ddad image.

**Comment by wjlszhang** [comment]
> I think it's a relative depth. If you set the maximum depth as 100, which corresponds to 10 cm, then 20 is (20/100)*10cm. Usually, the median method is used to get the depth.

Thanks, but I haven't set the value for my own data, and it is just around 10cm, which is not accurate, any suggestion to get the absolute absolute depth?

**Comment by JiawangBian** [comment]
You can print the relative scale to your data when doing the evaluation. You can get it in your images with GT depth, and apply it to new images without GT.

https://github.com/JiawangBian/sc_depth_pl/blob/308699c5b13c86f51eae4616ab5b8818f1116623/eval_depth.py#L169

**Comment by wjlszhang** [comment]
> 

Thanks Bian，however，I haven't GT depth in my dataset, is it still working?

**Comment by JiawangBian** [comment]
At least you need one GT-depth or GT-pose. Otherwise, it is impossible to get absolute depth in a monocular vision setting. 

> > 
> 
> Thanks @JiawangBian ，however，I haven't GT depth in my dataset during training, is above still working? p.s. I used '--val_mode photo' parameter during training.

**Comment by wjlszhang** [comment]
thank you，Bian

**Comment by chunqizhang** [comment]
> No, I haven't that error, you may fix it by resize your image size with the same as ddad image.

You are right! thank you for your advice
