### ISSUE TITLE
Read GT depth

### ISSUE THREAD

**Issue by chunqizhang** [JiawangBian/sc_depth_pl#36]
Thank you for your great work!
When I try to load gt depth, I have a question, what's the meaning of "/5000" and "/1000“ in the following comments? Where did they come from? By the way, when using LerEs to generating Pseudo-depth, what's the meaning of "*60000"?
@JiawangBian Thank you very much!
```
# load gt depth
            if args.dataset in ['nyu']:
                gt_depths[i] = imread(gt_depths[i]).astype(np.float32) / 5000
            elif args.dataset in ['scannet', 'bonn', 'tum']:
                gt_depths[i] = imread(gt_depths[i]).astype(np.float32) / 1000
            elif args.dataset == 'kitti':
                gt_depths[i] = np.load(gt_depths[i])
```

`cv2.imwrite(os.path.join(image_dir_out, img_name[:-4]+'-depth_raw.png'), (pred_depth_ori/pred_depth_ori.max() * 60000).astype(np.uint16))`

**Comment by JiawangBian** [comment]
It is based on how you store the GT depth. As we use the 'png' format to save the depth, it cannot save the float value. So we multiply a factor (1000 or 5000) to save the int number and then divided the depth by it to restore the original value.

For leres, as the max value of the 16bit 'png' map is 2**16' (65536). We simply set the factor as 60000.

**Comment by chunqizhang** [comment]
> It is based on how you store the GT depth. As we use the 'png' format to save the depth, it cannot save the float value. So we multiply a factor (1000 or 5000) to save the int number and then divided the depth by it to restore the original value.
> 
> For leres, as the max value of the 16bit 'png' map is 2**16' (65536). We simply set the factor as 60000.

Thank you so much for your reply. I store the gt depth by .npy file, can you tell me what is the "crop_mask"? Since there are four numbers in Kitti, should I change them when I compute errors?

```
#compute errors
    if dataset == 'kitti':
        crop_mask = gt[0] != gt[0]
        y1, y2 = int(0.40810811 * gt.size(1)), int(0.99189189 * gt.size(1))
        x1, x2 = int(0.03594771 * gt.size(2)), int(0.96405229 * gt.size(2))
        crop_mask[y1:y2, x1:x2] = 1
        max_depth = 80

    if dataset == 'nyu':
        crop_mask = gt[0] != gt[0]
        crop = np.array([45, 471, 41, 601]).astype(np.int32)
        crop_mask[crop[0]:crop[1], crop[2]:crop[3]] = 1
        max_depth = 10

    if dataset == 'ddad':
        crop_mask = gt[0] != gt[0]
        crop_mask[:, :] = 1
        max_depth = 200
```

**Comment by wjlszhang** [comment]
Hi, @JiawangBian @chunqizhang 

I have a similary question here, 

I plan to train my data with GT depth, and most of the depth values in the depth  file are aournd 500~2000, but there also includes invalid values: 65535, meaning the depth at those points haven't been caught . 

I wonder if I can set the max_depth with 2000 as below? ('th' is my dataset)

    if dataset == 'th':
        crop_mask = gt[0] != gt[0]
        crop_mask[:, :] = 1
        max_depth = 2000

Thanks so much

**Comment by JiawangBian** [comment]
> > It is based on how you store the GT depth. As we use the 'png' format to save the depth, it cannot save the float value. So we multiply a factor (1000 or 5000) to save the int number and then divided the depth by it to restore the original value.
> > For leres, as the max value of the 16bit 'png' map is 2**16' (65536). We simply set the factor as 60000.
> 
> Thank you so much for your reply. I store the gt depth by .npy file, can you tell me what is the "crop_mask"? Since there are four numbers in Kitti, should I change them when I compute errors?@JiawangBian
> 
> ```
> #compute errors
>     if dataset == 'kitti':
>         crop_mask = gt[0] != gt[0]
>         y1, y2 = int(0.40810811 * gt.size(1)), int(0.99189189 * gt.size(1))
>         x1, x2 = int(0.03594771 * gt.size(2)), int(0.96405229 * gt.size(2))
>         crop_mask[y1:y2, x1:x2] = 1
>         max_depth = 80
> 
>     if dataset == 'nyu':
>         crop_mask = gt[0] != gt[0]
>         crop = np.array([45, 471, 41, 601]).astype(np.int32)
>         crop_mask[crop[0]:crop[1], crop[2]:crop[3]] = 1
>         max_depth = 10
> 
>     if dataset == 'ddad':
>         crop_mask = gt[0] != gt[0]
>         crop_mask[:, :] = 1
>         max_depth = 200
> ```

crop_mask is defined in a previous paper, so we have to use it for a fair comparison. For your own data, you do not need it.

**Comment by JiawangBian** [comment]
> Hi, @JiawangBian @chunqizhang
> 
> I have a similary question here,
> 
> I plan to train my data with GT depth, and most of the depth values in the depth file are aournd 500~2000, but there also includes invalid values: 65535, meaning the depth at those points haven't been caught .
> 
> I wonder if I can set the max_depth with 2000 as below? ('th' is my dataset)
> 
> ```
> if dataset == 'th':
>     crop_mask = gt[0] != gt[0]
>     crop_mask[:, :] = 1
>     max_depth = 2000
> ```
> 
> Thanks so much

Yes, it is OK. Please also remember to exclude invalid depth when you compute loss for training your models.
