### ISSUE TITLE
pseudo_depth in the data_modules.py

### ISSUE THREAD

**Issue by chunqizhang** [JiawangBian/sc_depth_pl#37]
Dear Dr.Bian,
I train on my dataset with --val_mode photo, but I find the with_pseudo_depth=False in the data_modules. If it is False, will the pseudo_depth generated by the Leres effect? 
Thank you very much for your patient reply!

```
elif self.hparams.hparams.val_mode == 'photo':
            self.val_dataset = TrainFolder(
                self.hparams.hparams.dataset_dir,
                train=False,
                transform=self.valid_transform,
                sequence_length=self.hparams.hparams.sequence_length,
                skip_frames=self.hparams.hparams.skip_frames,
                use_frame_index=self.hparams.hparams.use_frame_index,
                with_pseudo_depth=False
            )
```

**Comment by JiawangBian** [comment]
Pseudo-depth is only used for training. Here, for validation, I only use photometric loss, so the pseudo-depth is not used.

**Comment by chunqizhang** [comment]
> Pseudo-depth is only used for training. Here, for validation, I only use photometric loss, so the pseudo-depth is not used.

Thank you for your reply!
