### ISSUE TITLE
training time

### ISSUE THREAD

**Issue by fcntes** [JiawangBian/sc_depth_pl#4]
Hi,

We have tried to train the models by following "scripts/run_train.sh" on a single 2080Ti which is slightly worse than V100 performance.

Before training, we firstly change the value of "limit_train_batches"(train.py line 41) to 1.0 so that it can use all the images in one epoch. As a result, the number of the batches in each epoch is 3493. The processed dataset we used is downloaded through your link.
Another change is the "num_epochs" in the "scripts/run_train.sh". We use 50 epochs which is the same as the description in your article.

Then, we followed the "scripts/run_train.sh" to train on nyuv2. However, the total time here is about 15 hours and the time of each epoch is about 8 minutes. The time here is much less than the description in the paper, which is about 44 hours (section 6.3 Timing).

We are troubled by this problem and would like to seek your help in pointing out possible errors in our operation.

Thanks

**Comment by JiawangBian** [comment]
1. this is a reimplementation, and it is faster than the version that we used in the paper
2. Feel free to change the number of epochs, epoch_size, and batch size. You do not need to strictly follow the paper setting, and you just need to make sure that the training has converged. (get similar results in final several epochs)
3. If you have large memory, it would be better to increase the batch size, (12,16,24 are all good).
