### ISSUE TITLE
About static camera.

### ISSUE THREAD

**Issue by 777-en** [JiawangBian/sc_depth_pl#40]
Hi, thank you for your gorgeous work. Recently I am trying to apply SC-DepthV3 on my own dataset. I note that before trainning, it is required to subsample video frames (to have sufficient motion) for training, which will filter out static-camera frames. However, my video are actually taken under a static camera, similar to a monitoring camera. I am wondering what will happen if I train on such dataset? Will the program crash?

**Comment by JiawangBian** [comment]
It will not work, because depth is learned from camera motion. When there is no camera motion, it is impossible to learn depth.
