### ISSUE TITLE
Is it possible to get indoor depth without gt or retraining?

### ISSUE THREAD

**Issue by gozi1123** [JiawangBian/sc_depth_pl#41]
I understand that I need a scaling factor to scale the model's predictions, but I don't have a GT depth map (I only want to do inference), so I can't get a median of the GT.
I can however get the maximum depth inside a room, can I somehow use it to get the absolute distance in the frame?
Let's say the wall of the room is 5 meters away from the camera, other objects (or people) are closer, but I don't know how much closer... will doing something like 
depth = (depth / depth.max()) * 5  # 5 meters....
work?

**Comment by JiawangBian** [comment]
It is OK but not accurate.
