### ISSUE TITLE
why? self.alpha = 10  self.beta = 0.01

### ISSUE THREAD

**Issue by yangtf-210310** [JiawangBian/sc_depth_pl#43]
class DepthDecoder(nn.Module):
    def __init__(self, num_ch_enc, scales=range(4), num_output_channels=1, use_skips=True):
        super(DepthDecoder, self).__init__()

        self.alpha = 10
        self.beta = 0.01

why?

**Comment by JiawangBian** [comment]
To control the predicted depth range.
