### ISSUE TITLE
i am trying to use own dataset I don't have "cam.txt (3x3 camera intrinsic matrix)" and also ground truths

### ISSUE THREAD

**Issue by SaiTeja2919** [JiawangBian/sc_depth_pl#57]

**Comment by JiawangBian** [comment]
Ground-truth depth is only used for evaluation, which is not necessary. 

If you don't have 'cam.txt' you can do camera calibration by using Matlab tools (https://www.mathworks.com/help/vision/camera-calibration.html)
You need to scan the checkboard using your camera

**Comment by LWQ2EDU** [comment]
I got my dataset from cameras of different types of cell phones. It's impassable to do camera calibration in this situation. How badly will it affect the indoor depth estimation result if I use an imprecise intrinsic matrix?

**Comment by JiawangBian** [comment]
maybe you can choose several images from each sequence and run COLMAP to obtain the camera intrinsics. I think that the method can work well even when your camera intrinsic is not accurate.
