### ISSUE TITLE
how to train posenet? solve position drift for static scene

### ISSUE THREAD

**Issue by stihuangyuan** [JiawangBian/sc_depth_pl#58]
SC_DepthV3 train depth net and pose net together, can i use this pose net output for slam?
For my application, i use pose net for camera real time location。but i find posenet position continuously drift farther away, even though camera actualy keep static.
how could i solve this problem ? thanks for you suggestion.

**Comment by JiawangBian** [comment]
Posenet is not sufficiently accurate. You may use the predicted depth within DFVO framework (https://github.com/Huangying-Zhan/DF-VO) for pose estimation.

**Comment by zhangjy328** [comment]
> SC_DepthV3 train depth net and pose net together, can i use this pose net output for slam? For my application, i use pose net for camera real time location。but i find posenet position continuously drift farther away, even though camera actualy keep static. how could i solve this problem ? thanks for you suggestion.

你好，我也想使用pose net，我想请教一下在这个模型中，你是在哪获得pose net训练结果并如何使用的？
Hello, I also want to use pose net. I would like to ask where you obtained the pose net training results in this model?
