### ISSUE TITLE
about preprocessed nyu depth dataset

### ISSUE THREAD

**Issue by JoeYangRL** [JiawangBian/sc_depth_pl#70]
Very innovative work and all! @JiawangBian
I have a few small questions about the preprocessed NYU Depth V2 dataset you provided:
1. Does the preprocessing you've done to this dataset include sub-sampling and weak rectification as described in Section 4.1 of the SC-Depth-V2 paper? Or is it just a sampled version of the original dataset?
2. What is the relationship between weak rectification and the proposed ARN network? Should we choose one to activate or use them simultaneously?

Thank you very much.

**Comment by JiawangBian** [comment]
Thanks for your interest. In the TPAMI paper, we use weak rectification to validate our idea only, where the proposed ARN is the differentiable version of weak rectification and automatically rectifies images during training.  
1. The processed NYU is just a sampled version of the original dataset. 
2. You do not need to do weak rectification before training.

**Comment by JoeYangRL** [comment]
Thank you for your quick respond. I have an additional question to bother: 
![image](https://github.com/JiawangBian/sc_depth_pl/assets/35392627/764b470e-9292-4b90-9f65-d4ee8238828e)
Here you mentioned "pair each image with its following k frames", does it equal to set sequence_length=10 in the generate_sample_index fucntion in train_folders.py shown below?
![image](https://github.com/JiawangBian/sc_depth_pl/assets/35392627/45fae94a-5ef2-4259-b139-d493f04f6d4e)

**Comment by JiawangBian** [comment]
No. the sampling is for weak rectification. You do not need to do that.

**Comment by JoeYangRL** [comment]
That clears up my confusions. Thank you so much.
