### ISSUE TITLE
Is it a toy dataset provided in the readme? It only contains 15k frames.

### ISSUE THREAD

**Issue by daydreamer2023** [JiawangBian/sc_depth_pl#8]
![image](https://user-images.githubusercontent.com/19202609/160089690-660bb712-7045-46b7-8988-1b5caa990dd5.png)
![image](https://user-images.githubusercontent.com/19202609/160089877-acd7a9d6-a921-4a07-80e9-b7297747ca4e.png)

**Comment by JiawangBian** [comment]
It is the full dataset. I did experiments on the current data, and you can reproduce the results on it.

**Comment by daydreamer2023** [comment]
By the way, Can you give some suggestion about how to train the `sc_depth.py` with the [dataset](https://onedrive.live.com/?cid=36712431a95e7a25&id=36712431A95E7A25%213269&authkey=%21AADmESW%2DFleeo6c) provided in this repo? 
I have  successfully reproduced the results of `kitti_scv1_model`, but failed to train a `nyu_scv1_model` version. I tried making some changes, but the model still doesn't converge.

**Comment by daydreamer2023** [comment]
Thanks for your quick reply！
I have successfully reproduced your results as listed in the reademe. But there may be a slight difference from the paper, but it doesn't hurt.
![image](https://user-images.githubusercontent.com/19202609/160164783-cabe2e3f-8b39-4033-9f93-7fe0c5696e98.png)
I run the `test.py` with [[nyu_scv2_model]](https://1drv.ms/u/s!AiV6XqkxJHE2mUSxFrPz690xaxwH?e=wFOR6A), and found the depth prediction at the bottom of the image is anomalous. Is this the reason why the performance is not the same as mentioned in the paper?

![image](https://user-images.githubusercontent.com/19202609/160165568-efbec5f5-8987-4192-a135-dca30101c496.png)
![image](https://user-images.githubusercontent.com/19202609/160165965-474bc0a8-588e-428f-acf0-8a5d3c0fcc55.png)
#--------------------------------------------------------------------------------------------------------------------------------------------------------------#
#--------------------------------------------------------------------------------------------------------------------------------------------------------------#
By the way, Can you give some suggestion about how to train the sc_depth.py with the [dataset](https://onedrive.live.com/?cid=36712431a95e7a25&id=36712431A95E7A25%213269&authkey=%21AADmESW%2DFleeo6c) provided in this repo?
I have successfully reproduced the results of kitti_scv1_model, but failed to train a `Ours-DP` version. I tried making some changes, but the model still doesn't converge.
#--------------------------------------------------------------------------------------------------------------------------------------------------------------#
#--------------------------------------------------------------------------------------------------------------------------------------------------------------#
One more question. This dataset(as metioned 'directly on original data with ARN') is indeed smaller than what you gave earlier（pre-processed 67K rectified pairs）. Shouldn't it be bigger than that?

**Comment by JiawangBian** [comment]
[the bottom of the image is anomalous.] It is the issue of images of NYU datasets. You can find every image has a white board. 

[but failed to train a Ours-DP version] Indeed you do not need to do that because the ARN version is better than DP. DP is just used to verify the idea, and it is not an elegant method.  If you want to propose new methods based on this paper, you can only work on the ARN version. 

[pre-processed 67K rectified pairs] Should not. 67K pairs are constructed by pairing each image with their neighboring 20 images (some are deleted). It is just a data preprocessing method. You can directly on original video data by using ARN and achieve similar results.

**Comment by Cresynia** [comment]
Hello! I met the same problems as you when I ran the test.py with nyu_scv2_model, I couldn't get the right results as the paper. 
![image](https://github.com/JiawangBian/sc_depth_pl/assets/90834089/2fe19166-656a-4152-bd15-f5b06253e19c)

Do you know how to resolve it? Thanks!
